import type { Metadata } from "next";
import { Cutive_Mono, Dosis, Geist, Geist_Mono, Syne_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cutive_mono = Cutive_Mono({
  variable: "--font-cutive-mono",
  subsets: ["latin-ext", "latin"],
  weight: ["400"],
});

const syneMono = Syne_Mono({
  variable: "--font-syne-mono",
  subsets: ["latin"],
  weight: ["400"],
});
const dosis = Dosis({
  variable:"--font-dosis",
  subsets:["latin","latin-ext"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dosis.variable} ${syneMono.variable} ${cutive_mono.variable} antialiased`}
      >
        <main
          className="absolute inset-0 -z-10 w-lvw h-lvh 
          bg-[linear-gradient(to_right,rgba(255,255,255,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.08)_1px,transparent_1px)] 
          bg-[length:calc(100%/6)_calc(100%/8)] 
          md:bg-[length:calc(100%/12)_calc(100%/12)] 
          bg-red-"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
